### PR TITLE
Add hackney:start() to shell instructions, use ok atom in response

### PR DESCRIPTION
**Pull request by shaneutt**
Just some simple instruction updates in the README.

### CODE REVIEW

**Comment by ipinak** [comment]
Are you sure that `hackney` doesn't start? Based on this file https://github.com/julienXX/slacker/blob/master/src/slacker.erl `hackney:start()` is called when you call `slacker:start()`.

**Comment by ipinak** [comment]
To be honest none of the `start` functions should be used in OTP applications. However `restclient` was not starting the dependencies properly in the `app.src` file as it should, therefore slacker had to do that for the system to work. From what I see they have fixed this and restclient properly starts them, so maybe the library needs a small refactoring.

**Comment by shaneutt** [comment]
To your first point, I can confirm with `rebar3 shell` specifically I have to run hackney:start().

Here is the error I receive:

```
$ rebar3 shell
===> Verifying dependencies...
===> Compiling slacker
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:0] [kernel-poll:false]

Eshell V8.1  (abort with ^G)
1> slacker:start().
ok
4> {Ok, Status, Headers, Body} = slacker_user:list(Token, Options).
** exception exit: {noproc,{gen_server,call,
                                       [hackney_manager,
                                        {new_request,<0.161.0>,#Ref<0.0.1.2577>,
                                                     {client,undefined,
                                                             {metrics_ng,metrics_dummy},
                                                             hackney_ssl_transport,"slack.com",443,<<"slack.com">>,[],
                                                             nil,nil,nil,true,hackney_pool,5000,false,5,false,5,...}},
                                        infinity]}}
```

If you follow it up with a hackney:start():

```
5> hackney:start().
ok
6> {Ok, Status, Headers, Body} = slacker_user:list(Token, Options), ok.
ok
```

**Comment by julienXX** [comment]
Thanks! I'll bump the restclient version and see if it fixes the issue.

**Comment by julienXX** [comment]
Bumping restclient version does not solve the issue and this does not occur using rebar 2. Not sure why.

**Comment by marco-m** [comment]
I can confirm I have the same problem starting with `rebar3 shell`. The solution I used is slightly different, `application:ensure_all_started(slacker).`

Although using `hackney:start().` or `application:ensure_all_started(slacker).`, I think that adding this workaround in the documentation is better than leaving people wondering what to do, then forking Slacker to provide a PR to change the docs, then stumbling upon this PR :-)

**Comment by julienXX** [comment]
Thanks @marco-m !

**Comment by julienXX** [comment]
Ok I updated the README. Thanks all!

**Comment by marco-m** [comment]
merci!

**Pull request closed without merging**
